
### Create expense Request

POST /api/expenses
Host: localhost:3000
Content-Type: application/json

{
    "name": "Expense Name"
}

### Request with Trailing slash

POST /api/expenses/
Host: localhost:3000
Content-Type: application/json

{
    "name": "Expense Name"
}

### List Expenses
GET /api/expenses?page=1&size=10
Host: localhost:3000
Content-Type: application/json

### List Expenses Invalid Request
GET /api/expenses?page=1&size=0
Host: localhost:3000
Content-Type: application/json
